version: '3'
services:
        client:
                image: react-fe
                restart: always
                ports:
                        - "3000:3000"
                volumes:
                        - ./client:/client
                        - /client/node_modules
                links:
                        - api
                networks:
                        - webappnetwork
        api:
                image: node-be
                restart: always
                ports:
                        - "3001:3001"
                volumes:
                        - ./api:/api
                        - /api/node_modules
                depends_on:
                        - mysql
                networks:
                        - webappnetwork
        mysql:
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_DATABASE: 'db'
                        MYSQL_USER: 'site'
                        MYSQL_PASSWORD: 'password'
                        MYSQL_ROOT_PASSWORD: 'password'
                ports:
                        - "53306:3306"
                expose:
                        - "3306"
                networks:
                        - webappnetwork
networks:
        webappnetwork:
                driver: bridge
